name: flet_blur
description: Flet Blur control
repository: https://github.com/shiena/flet-blur/src/flutter/flet_blur
version: 0.3.0
homepage: https://github.com/shiena/flet-blur

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 0.27.0
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
